language: python
matrix:
  fast_finish: true
  include:
    - python: "3.7"
      env: TOXENV=pylint
      dist: xenial
    - python: "3.7"
      env: TOXENV=lint
      dist: xenial
    - python: "3.7"
      env: TOXENV=cov
      dist: xenial
      after_success: coveralls
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.7"
      env: TOXENV=py37
      dist: xenial
install: pip install -U tox coveralls
script: tox
deploy:
  provider: pypi
  user: andrewsayre
  password:
    secure: Cxy/irGC8fQR+cd+J8L4oZs8Y1rKY7yocEaL4YtPFlHctb9B9Sgdubwts3f4DUmMPD4L5U/bH0FRv2jy5UUfYXvcqTAFYkWrsDcW2tUHEfy+3DqpCEBVt84pdm3ARh5YiJIuN7mKe76573QuYPYfVj/XIBn4bKSu/5fa9u5iTMkO29rSC0NZci/DkuxnwxMl0xtcf12J5RES1ZMsEkgdsfCWTRuCCgTfMLBFv9xoR6VCZqm4JyXVJpaBdX5peStIMN6SrebPF4V2Wjbmg0edqHXzdOjCRzC1nHzt4itLkmra4w2dfoGfmcpr714RBBTv8OI8OLT1yJhZGZmVaXDoAEy/HMvMOeVdINbxGeP6Sm6Lv2T2Z7fGJgcx115cH/mlCSz3jjRDrZ4YRH2/xgKfbAPl16kyQmXDlHQwb7oD+yO1LdVtBRcqy6aYKKGUiUXxI3W1iI05rXVMxdjHlTsr1qinBTUyO9628NLGF8rQAnmsGXBq6BmXrmyRqR3KjWpqq7NPugfwGsoVztEDGZ3hQzTBAKjr2TY/VYhr+XHpApvLCCvqwtk1na1MAByDV4E9jtPnT/sVzGknpc7TBcPo8a6sd1I+9n6WdCZymHEt/Cd5bEJZi3AtnmmAx1HUJCGAk84WehWjgNwpIuwXdnjUzeiNi8xuunHd21CRsOSYUV4=
  distributions: sdist bdist_wheel
  skip_existing: true
  on:
    tags: true
